//Product Actions-types 
//Get product
export const GET_PRODUCT_LOAD = "GET_PRODUCT_LOAD";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";
export const GET_PRODUCT_RESET = "GET_PRODUCT_RESET";

export const GET_PRODUCTS_LOAD = "GET_PRODUCTS_LOAD";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const EDIT_PRODUCT_LOAD = "EDIT_PRODUCT_LOAD";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAIL = "EDIT_PRODUCT_FAIL";


export const FETCH_PRODUCTS_BY_CATEGORY = "FETCH_PRODUCT_BY_CATEGORY";
export const ORDER_PRODUCTS_BY_PRICE = "ORDER_PRODUCTS_BY_PRICE";
